triggers:
- description: null
  envs: []
  last_enabled_at: 2024-09-10 15:46:02.960828+00:00
  name: 'Retrain models hourly '
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-09-09 01:34:00+00:00
  status: active
  token: 1e23f063a5354abb83124b5818f5f784
  variables: {}
